import { definePrototypeComponentRegistry } from "proto-plugin";

export const PROTO_PARTNER_PAGE_COMPONENT_IDS = [
  "page",
  "scroll-container",
  "partner-shape-canvas",
  "partner-page-flow-block",
  "partner-page-flow-block.partner-page-back-button",
  "partner-page-nav-button.partner-page-back-button",
  "submit-shape-modal",
  "submit-shape-modal-block",
  "submit-shape-modal.partner-shape-canvas",
  "submit-modal-variant-toggle",
  "submit-modal-card-texture-background",
  "submit-modal-layouts.submit-modal-actions",
  "submit-modal-explorer",
  "submit-modal-variant-tabs",
  "submit-modal-mobbin-inspiration-gallery",
  "partner-page-motion.partner-motion-fade-up",
  "partner-page-motion.partner-motion-spring-pop",
  "partner-page-motion.partner-motion-spring-button",
  "proto-shape-customizer-block",
  "proto-shape-icons.proto-shape-icon",
  "proto-shape-icons.proto-color-swatch",
  "proto-shape-icons.proto-texture-swatch",
  "invite-copy-block",
  "invite-copy-block.invite-follow-up-copy",
  "invite-copy-block.invite-follow-up-title",
  "invite-copy-block.invite-follow-up-body",
  "invite-copy-block.invite-follow-up-content",
  "invite-eyebrow-header",
  "invite-eyebrow-header.animated-invite-eyebrow-header",
  "invite-follow-up-nav",
  "invite-follow-up-shape-examples",
  "creator-attribution-block",
  "creator-attribution-variant-toggle",
  "creator-attribution-explorer",
  "creator-attribution-variant-tabs",
  "invite-follow-up-shape-layout-variant-toggle",
  "invite-follow-up-shape-layout-explorer",
  "invite-follow-up-shape-layout-variant-tabs",
  "invite-animations-block",
  "invite-animations-variant-toggle",
  "invite-animations-explorer",
  "invite-animations-variant-tabs",
  "invite-animations-mobbin-inspiration-gallery",
  "invite-copy-variant-toggle",
  "invite-copy-explorer",
  "invite-copy-variant-tabs",
  "mobbin-inspiration-gallery",
  "proto-shapes-variant-toggle",
  "proto-shapes-explorer",
  "proto-shapes-variant-tabs",
  "protoshapes-mobbin-inspiration-gallery",
  "shape-color-picker-block",
  "shape-color-picker-block.shape-color-picker-controls",
  "shape-color-picker-variant-toggle",
  "shape-color-picker-explorer",
  "shape-color-picker-variant-tabs",
  "shape-color-picker-mobbin-inspiration-gallery",
  "mobile-picker-layout-block",
  "mobile-picker-layout-block.mobile-picker-layout-controls",
  "mobile-picker-layout-variant-toggle",
  "mobile-picker-layout-explorer",
  "mobile-picker-layout-variant-tabs",
  "mobile-picker-layout-mobbin-inspiration-gallery",
  "mobile-panel-motion-block",
  "mobile-panel-motion-shell",
  "mobile-panel-motion-variant-toggle",
  "mobile-panel-motion-explorer",
  "mobile-panel-motion-variant-tabs",
  "mobile-panel-motion-mobbin-inspiration-gallery",
] as const;

/** Nested ids from PrototypeVariantExplorer / PrototypeDesignBriefPanel. */
export const DYNAMIC_TARGET_PREFIXES = [
  "submit-modal-explorer.",
  "submit-modal-variant-tabs.",
  "submit-modal-mobbin-inspiration-gallery.",
  "invite-animations-explorer.",
  "invite-animations-variant-tabs.",
  "invite-animations-mobbin-inspiration-gallery.",
  "invite-copy-explorer.",
  "invite-copy-variant-tabs.",
  "creator-attribution-explorer.",
  "creator-attribution-variant-tabs.",
  "invite-follow-up-shape-layout-explorer.",
  "invite-follow-up-shape-layout-variant-tabs.",
  "mobbin-inspiration-gallery.",
  "proto-shapes-explorer.",
  "proto-shapes-variant-tabs.",
  "protoshapes-mobbin-inspiration-gallery.",
  "shape-color-picker-explorer.",
  "shape-color-picker-variant-tabs.",
  "shape-color-picker-mobbin-inspiration-gallery.",
  "mobile-picker-layout-explorer.",
  "mobile-picker-layout-variant-tabs.",
  "mobile-picker-layout-mobbin-inspiration-gallery.",
  "mobile-panel-motion-explorer.",
  "mobile-panel-motion-variant-tabs.",
  "mobile-panel-motion-mobbin-inspiration-gallery.",
] as const;

export const protoPartnerPageComponentRegistry = definePrototypeComponentRegistry({
  ids: PROTO_PARTNER_PAGE_COMPONENT_IDS,
  dynamicPrefixes: DYNAMIC_TARGET_PREFIXES,
});
